name: Test and push
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.4'
      - name: Install Yarn
        run: |
          npm install -g yarn
      - name: Git configuration
        run: |
          git config --global user.email 'sakk7e+dev@gmail.com'
          git config --global user.name 'k07e'
      - name: Test and push
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          yarn test \
            && git clone https://github.com/k07e/nvim-config.lua dist \
            && yarn build \
            && cd dist \
            && if [ "$(git ls-files --exclude-standard -mo | wc -l)" -gt 0 ]; then
              git add -A \
                && git commit -m 'Auto commit after yarn build' \
                && git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/k07e/nvim-config.lua.git \
                && git push -u origin main
            fi
